# Common FreeRTOS+TCP
CFILES_FREERTOS_PLUS_TCP_BASE =  FreeRTOS_ARP.c
CFILES_FREERTOS_PLUS_TCP_BASE += FreeRTOS_DHCP.c
CFILES_FREERTOS_PLUS_TCP_BASE += FreeRTOS_DNS.c
CFILES_FREERTOS_PLUS_TCP_BASE += FreeRTOS_IP.c
CFILES_FREERTOS_PLUS_TCP_BASE += FreeRTOS_Sockets.c
CFILES_FREERTOS_PLUS_TCP_BASE += FreeRTOS_Stream_Buffer.c
CFILES_FREERTOS_PLUS_TCP_BASE += FreeRTOS_TCP_IP.c
CFILES_FREERTOS_PLUS_TCP_BASE += FreeRTOS_TCP_WIN.c
CFILES_FREERTOS_PLUS_TCP_BASE += FreeRTOS_UDP_IP.c

# Network buffer allocation scheme 
CFILES_FREERTOS_PLUS_TCP_BUFFER = BufferAllocation_2.c

# Shall be included in the project Makefile
CFILES_FREERTOS_PLUS_TCP = $(CFILES_FREERTOS_PLUS_TCP_BASE) $(CFILES_FREERTOS_PLUS_TCP_BUFFER)
