PROJECT = ssd1306_freertos

CFILES = ssd1306_freertos.c
CFILES += uart.c uart_stdio.c dwt_delay.c ssd1306.c
CFILES += $(CFILES_FREERTOS) $(CFILES_FREERTOS_HEAP_4)

include ../../freertos.mk
include ../../rules.mk
