PROJECT = irdecode_freertos

CFILES = irdecode_freertos.c
CFILES += uart.c uart_stdio.c ir_nec.c
CFILES += $(CFILES_FREERTOS) $(CFILES_FREERTOS_HEAP_4)

include ../../freertos.mk
include ../../rules.mk
